### ISSUE TITLE
Update to Connection String

### ISSUE THREAD

**Issue by JN-ICS** [thycotic/ssi-docs#30]
Document: (https://docs.thycotic.com/ssi/1.0.0/sap/sap-hana/config/password-changer.md)

Step 4: Should use the following string: DRIVER={HDBODBC};UID=$USERNAME;PWD=$PASSWORD;SERVERNODE=$SERVER

Remove the braces from everything except for HDBODBC
Also, it should be noted that Servernode typically uses server:port.  For example, when testing the password changing function when putting in server use something like this: servername:30015

**Comment by danigran** [comment]
Resolved with the documentation update on 4/20/2021.

Thank you for submitting the issue and helping us improve our documentation.
